awa/go-iap

appstore/validator.go
appstore/validator_test.go

In the gorequest Send method, there is a switch that checks the type of the parameter (https://github.com/parnurzeal/gorequest/blob/master/main.go#L341). In this particular case, the type of *IAPRequest is "ptr" which results in gorequest's switch to go the default case which is empty. The request was made with an empty body.

gorequest wasn't sending the request for validation

---

appstore/model.go

These fields are not documented in official document of Apple. However, they are present in API response.
Other OSS validators such as [venice](https://github.com/nomad/Venice) have their fields, so I will add them.

Added some fields for auto-renewable subscription

---

Makefile
README.md

This adds an amazon package which adds support for [RVS for IAP v2.0](https://developer.amazon.com/public/apis/earn/in-app-purchasing/docs-v2/verifying-receipts-in-iap-2.0)

Add Support for the Amazon Receipt Verification Service

---

appstore/validator.go

Interface IAPClient and its implementation Client no longer match since the updates to Client in https://github.com/dogenzaka/go-iap/commit/e9d5da1f8f6bff09e3f0ff777a44fe617e45ae52

Update IAPClient.Verify to use interface argument

---

README.md
playstore/validator.go

Context is now a Standard Go library.
So I replace golang.org/x/net/context with it.

Use standard context package

---

appstore/subscription.go

These are app store subscription notify model.
The fields `password`, `original_transaction_id`, `auto_renew_adam_id` don't show in raw notify body but exist in the document.
And I don't have raw notify body when notification_type is `RENEWAL` or `INTERACTIVE_RENEWAL` or `DID_CHANGE_RENEWAL_PREFERENCE`.
Can anyone check for what is missing or error?
Refer:
https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/StoreKitGuide/Chapters/Subscriptions.html#//apple_ref/doc/uid/TP40008267-CH7-SW16

add app store subscription notify model

---

appstore/model.go
appstore/validator.go
appstore/validator_test.go

According to https://developer.apple.com/library/content/technotes/tn2413/_index.html#//apple_ref/doc/uid/DTS40016228-CH1-RECEIPTURL
Always verify your receipt first with the production URL; proceed to verify with the sandbox URL if you receive a 21007 status code. Following this approach ensures that you do not have to switch between URLs while your application is being tested or reviewed in the sandbox or is live in the App Store.

Have app store hit prod and then sandbox if 21007

---

appstore/model.go
appstore/notification.go

In-App Receipt doesn't use "PROD" but use "Production" as environment.
So I fixed constants.

Fixed environmental constants

---

appstore/model.go

According to https://developer.apple.com/library/content/releasenotes/General/ValidateAppStoreReceipt/Chapters/ReceiptFields.html and https://developer.apple.com/library/content/releasenotes/General/ValidateAppStoreReceipt/Chapters/ValidateRemotely.html , some keys need not to be included in IAP responses. So I added "omitempty" to these keys.
* `expire_date` is only present for auto-renewable subscription receipts.
* `cancelation_date` and `cancelation_reason` are only for a canceled transaction.
* `web_order_line_item_id` is for identifying cross devices purchase events.
* `latest_receipt` is only for  auto-renewable subscriptions.
* `pending_renewal_info` is only for auto-renewable subscriptions..
* `is-retryable` is only for status codes 21100-21199.
Please check it.

Add "omitempty" to some keys which need not to be returned

---

appstore/model.go

I've added iOS6 style receipt struct.
This is because ``statusUpdateNotification``'s ``latest_receipt`` format is iOS6 style.
The raw receipt is following.
```
{
"auto_renew_product_id": "xxx",
"auto_renew_status": 0,
"expiration_intent": "1",
"is_in_billing_retry_period": "0",
"latest_expired_receipt_info": {
"app_item_id": "xxx",
"bid": "xxx",
"bvrs": "xxx",
"expires_date": "1520904882000",
"expires_date_formatted": "2018-03-13 01:34:42 Etc/GMT",
"expires_date_formatted_pst": "2018-03-12 18:34:42 America/Los_Angeles",
"is_trial_period": "true",
"is_in_intro_offer_period": "false",
"item_id": "xxx",
"product_id": "xxx",
"purchase_date": "2017-12-13 02:34:42 Etc/GMT",
"purchase_date_ms": "1513132482000",
"purchase_date_pst": "2017-12-12 18:34:42 America/Los_Angeles", …
```

Added iOS6 style receipt

---

appstore/model.go

When the subscription is under billing problem, there are cancellation date fields in raw receipt.
```
{
"auto_renew_product_id": "xxx",
"auto_renew_status": 1,
"cancellation_date": "2017-09-15 09:14:26 Etc/GMT",
"cancellation_reason": "0",
"expiration_intent": "2",
"latest_expired_receipt_info": {
"app_item_id": "xxx",
"bid": "xxx",
"bvrs": "xxx",
"cancellation_date": "2017-09-15 09:14:26 Etc/GMT",
"cancellation_date_ms": "1505466866000",
"cancellation_date_pst": "2017-09-15 02:14:26 America/Los_Angeles",
"expires_date": "1505170657000",
"expires_date_formatted": "2017-09-11 22:57:37 Etc/GMT",
"expires_date_formatted_pst": "2017-09-11 15:57:37 America/Los_Angeles",
"item_id": "xxx",
"original_purchase_date": "2016-08-11 22:57:40 Etc/GMT",
"original_purchase_date_ms": "1470956260000", …
```

Added cancellation date fields

---

README.md
appstore/validator.go
appstore/validator_test.go
playstore/validator.go
playstore/validator_test.go

resolve #61 
The following test ensures that the cancellation works.
https://github.com/awa/go-iap/compare/master...jun06t:context?expand=1#diff-821c99a26e8982efee8b6b0c363368f9R140

Support context package when requesting AppStore

---

amazon/validator.go
amazon/validator_test.go
appstore/validator.go
appstore/validator_test.go
playstore/validator.go
playstore/validator_test.go

The http document says "A Timeout of zero means no timeout".
>         // Timeout specifies a time limit for requests made by this
>         // Client. The timeout includes connection time, any
>         // redirects, and reading the response body. The timer remains
>         // running after Get, Head, Post, or Do return and will
>         // interrupt reading of the Response.Body.
>         //
>         // A Timeout of zero means no timeout.
https://golang.org/pkg/net/http/#Clientn
And DefaultClient is empty struct of Client.
```
var DefaultClient = &Client{}
```
So DefaultClient doesn't have timeout. It may stress the system heavily.

Added client timeout because http.DefaultClient doesn't have timeout

---

appstore/model.go

- Since `original_transaction_id` included in `pending_renewal_info` is not defined, it was added.

Add `pending_renewal_info.original_transaction_id` for Apple's receipt

---

amazon/validator.go
amazon/validator_test.go
appstore/validator.go

I found a few unhandled JSON encode/decode errors and added handling code in 46a2f52.
Let me know if the change in 92d5672 isn't wanted -- I can remove it from the PR -- but I think it's more helpful to return the error directly.

Minor Error Handling Fixes

---

appstore/model.go

Support grace period fields.
> If you choose to enable Billing Grace Period, ensure that you provide full service for the subscription throughout the grace period. You can check the ``grace_period_expires_date_ms`` field in the responseBody.Pending_renewal_info array of the receipt to determine the end of this grace period duration.
ref: https://developer.apple.com/documentation/storekit/in-app_purchase/reducing_involuntary_subscriber_churn?language=swift
Jacob already confirmed that the receipt has those new fields.
- grace_period_expires_date
- grace_period_expires_date_ms
- grace_period_expires_date_pst
ref: https://www.revenuecat.com/2019/09/13/supporting-ios-billing-grace-period

Added grace period fields

---

appstore/model.go
appstore/notification.go

Apple added a new property `unified_receipt` to their S2S notification that should be used instead of existing properties:
https://developer.apple.com/news/?id=11222019a
https://developer.apple.com/documentation/appstoreservernotifications/unified_receipt
Also, added some missing properties to `InApp` and new `DID_RECOVER` notification type that should be used instead of `RENEWAL`.

Adding unified receipt to the Apple S2S notification

---

appstore/notification.go

Since few days ago we noticed that Apple started returning `Status` of `NotificationUnifiedReceipt` as integer instead of string and so now we are getting errors like:
```
json: cannot unmarshal number into Go struct field NotificationUnifiedReceipt.unified_receipt.status of type string
```
Unified receipt docs: https://developer.apple.com/documentation/appstoreservernotifications/unified_receipt

Fixing NotificationUnifiedReceipt status type

---

appstore/notification.go

Deprecation comments added for the following top-level objects: latest_receipt, latest_receipt_info, latest_expired_receipt, latest_expired_receipt_info. Documentation: https://developer.apple.com/documentation/appstoreservernotifications/

Add SubscriptionNotification deprecation comments

---

appstore/model.go

As documented in https://developer.apple.com/documentation/appstorereceipts/responsebody/latest_receipt_info: 
> This field is only present for upgrade transactions.

appstore: Set IsUpgraded as omitempty

---

appstore/notification.go

Since receive notification type `"DID_FAIL_TO_RENEW"` is not defined, it added.
refs: https://developer.apple.com/documentation/appstoreservernotifications/notification_type

Add NotificationType "DID_FAIL_TO_RENEW"

---

.travis.yml
README.md
appstore/validator.go
appstore/validator_test.go

resolve #104
And I defined each error because we can use ``errors.Is()`` method from go 1.13 to assert errors.
https://blog.golang.org/go1.13-errors

Handle http status 5xx error

---

appstore/validator.go
appstore/validator_test.go

Apple servers sometimes takes more than the default time causing client timeouts, increase the default timeout to cater increases response times.
https://github.com/awa/go-iap/issues/123

increase default timeout for client

---

appstore/notification.go

Apple change ExpirationIntent from string to integer in server-to-server notification
https://developer.apple.com/documentation/appstoreservernotifications/responsebody

Apple change expiration_intent

---

appstore/model.go

- https://github.com/awa/go-iap/issues/153
- #157

Fix field type part of original_transaction_id to string

---

appstore/model.go
appstore/notification.go

Since yesterday we noticed that Apple is sending `OriginalTransactionID` sometimes as a string and sometimes as an integer.
So, I replaced `int64` with `numericString` which can handle such cases.
Related to: https://github.com/awa/go-iap/pull/157

Fixing Apple OriginalTransactionID type

---

.github/workflows/unit_test.yml
README.md
amazon/validator_test.go
go.mod

- remove support for go version 1.15, 1.16, 1.17

Supported Go versions 1.18 or later

---

README.md
appstore/api/model.go
appstore/api/store.go
appstore/api/token.go

Here are several changes for AppStore server api.
1. upgrade refund history API to v2 
2. add send consumption information api
3. update readme doc for code sample

feat(appstore): upgrade refund history api to v2 and add send consumption information api

---

README.md
appstore/api/model.go
appstore/api/store.go

1. add GetNotificationHistory and ExtendSubscriptionRenewalDate api for appstore api
2. format codes of readme document

feat(appstore): add GetNotificationHistory and ExtendSubscriptionRenewalDate api for appstore api 

---

amazon/validator.go
amazon/validator_test.go

Added missing RVS Response Fields
[Link](https://developer.amazon.com/docs/in-app-purchasing/iap-rvs-for-android-apps.html#rvs-response-syntax) to the official documentation of amazon for RVS response fields

Added missing RVS Response Fields

---

appstore/model.go

According to Apple developer [docs](https://developer.apple.com/documentation/appstorereceipts/responsebody/pending_renewal_info) there is a `promotional_offer_id` field indicating the promotional offer for an auto-renewable subscription.

add PendingRenewalInfo.PromotionalOfferID

---

appstore/model.go

fixed json tag to the. correct value based on the official documentation. 
`is-retryable -> is_retryable`
reference: 
https://developer.apple.com/documentation/appstorereceipts/responsebody

Fixed some JSON tags in IAP responses

---

hms/model.go

Per doc https://developer.huawei.com/consumer/en/doc/development/HMSCore-References/server-data-model-0000001050986133, add graceExpirationTime to hms model

feat(hms): add graceExpirationTime to hms model

---

appstore/validator.go
appstore/validator_test.go

Currently, in order to distinguish test receipts in iOS, there is one field Environment in iOS7 and higher. However, there is no explicit field to mark whether the receipt is a test or not for the iOS6 receipt. 
Originally, the field AppItemID was to be used to mark whether the receipt is test receipt or not for the iOS6 receipt. Unfortunately, this field was set in test receipt recently. It seems there is no explicit field to distinguish whether the receipt is test receipt or not. I post this PR to return the ErrReceiptIsForTest when the status is 21007, we could check if the receipt is test receipt through this error. 
Maybe there could be a more elegant way to solve it?

feat(ios): mark ios test receipt through ErrReceiptIsForTest

---

appstore/validator.go

apple verify receipt server a failure every few months.
We want to ignore recepit when apple server unhealthy.
So, add return http status code when 5xx.
https://developer.apple.com/system-status/

feat(ios) return http status code when 5xx error

---

appstore/cert.go
appstore/notification_v2.go
appstore/validator.go
playstore/validator_test.go

Try to resolve the issue https://github.com/awa/go-iap/issues/156,  add decode notification v2 body method to appstore

 feat(appstore): add decode notification v2 body method to appstore

---

appstore/api/error.go
appstore/api/error_test.go
appstore/api/store.go
go.mod
go.sum

The original implementation of returning `fmt.Errorf("appstore api: %v return status code %v", URL, statusCode)` provides too little information for developers to figure out what's happening.
The PR will bring these changes:
1. When calling `StoreClient.Do`, i only return the custom `Error` when status code is not 'OK' and the unmarshal is successful. So this will not change the behaviour that the callers to StoreClient.Do (`GetALLSubscriptionStatuses` etc.) still return error to further caller when status code is not 'OK'.
2. But maybe some developers using this library like regex matching the error message `appstore api: %v return status code %v", URL, statusCode` to get status code (no a good usage). So this is a breaking change for theses developers.

feat(appstore): return detailed error information out to caller

---

appstore/api/store.go

feat(appstore): add query parameters to get all all subscription status api. Per doc https://developer.apple.com/documentation/appstoreserverapi/get_all_subscription_statuses?changes=latest_minor

feat(appstore): add query parameters to get all all subscription status api

---

appstore/api/error.go
appstore/api/store.go

Per doc https://developer.apple.com/documentation/appstoreserverapi/identifying_rate_limits?changes=latest_minor , - Handle exceeded rate limits gracefully
- Check the Retry-After header if you receive the HTTP 429 error. This header contains a UNIX time, in milliseconds, that informs you when you can next send a request.
Retrieve the Retry-After header if you receive the HTTP 429 error, and put this value to error and return to the client for handle exceeded rate limits gracefully.

feat(appstore): add retryAfter to api error for handle exceeded rate limit

---

appstore/api/error.go

- https://github.com/awa/go-iap/pull/217#issuecomment-1612462192
feat(appstore): add RetryAfter method to Error to expose the `retryAfter`

feat(appstore): add RetryAfter method to Error

---

README.md

1. Add app store server api information to the readme
2. Mark the verifyReceipt of app store is deprecated.

docs(readme): add app store server api information to readme

---

README.md

-  add GetTransactionInfo sample to the README for iOS verification with app store api

docs(readme): add GetTransactionInfo sample

---

appstore/api/model.go
appstore/api/store.go

This PR brings following updates:
1. Fix the json tag of NotificationHistoryRequest.TransactionId, which should be omitempty. Otherwise the App Store Server API will return invalidTransactionId Error.
2. Breaking changes: Implement a single page version of get_notification_history and `GetAllNotificationHistory` will use it directly.
3. Per PR(https://github.com/awa/go-iap/pull/208), return detailed error first in `GetSubscriptionRenewalDataStatus`.
Btw, ff the 2nd update is approved, we may consider replace all the current implementation of history-like method, `GetTransactionHistory` etc.

fix and refactor appstore get_notification_history

---

appstore/api/model.go
appstore/api/store.go

Add  ParseJWSEncodeString to decode jws string, such as JWSTransaction and JWSRenewalInfoDecodedPayload decode.
Related issue: https://github.com/awa/go-iap/issues/227

feat(appstore): add ParseJWSEncodeString to decode jws string

---

appstore/notification_v2.go

`NotificationTyp2V2Test` corrected to `NotificationTypeV2Test`

Correct typo in const for test notification type

---

appstore/api/model.go

Try to resolve the issue https://github.com/awa/go-iap/issues/232

fix(appstore): modify JWSRenewalInfoDecodedPayload, JWSTransaction field type

---

playstore/notification.go

- https://developer.android.com/google/play/billing/rtdn-reference?hl=en#json_specification
- `eventTimeMillis` is long, but defined as string
- possible error when marshaling from JSON to struct

fix(googleplay): fix type for eventTimeMillis

---

appstore/api/model.go

Per doc https://developer.apple.com/documentation/appstoreserverapi/jwstransactiondecodedpayload?changes=latest_minor, the `price`, `concurrency` and OfferDiscountType are added into JWSTransction in the latest version.
https://github.com/awa/go-iap/issues/250

feat(appstore): add more fields to JWSTransaction

---

playstore/notification.go
playstore/validator_test.go

Add new notification type (`VoidedPurchaseNotification`) in playstore per doc: https://developer.android.com/google/play/billing/rtdn-reference#voided-purchase
Use `*VoidedPurchaseNotification` instead of `VoidedPurchaseNotification` as there is no `version` field inside `VoidedPurchaseNotification` like other notification types for developer to gracefully check if this specific type of notification is present.

feat(playstore): add VoidedPurchaseNotification in playstore notification

---

appstore/validator.go

Fixed possible nil pointer access in `(*appstore.Client).ParseNotificationV2` on token parse error.

fix(appstore): possible nil pointer access in ParseNotificationV2

---

appstore/model.go
appstore/model_test.go
appstore/notification.go

Hi AWA team !
Here at TextNow we use your repository in order to communicate with Apple and Google for our IAP.
While using this repository, we found some potentialk improvements regarding the use of `NumericString` type.
We are using these fixes for a while in our Production environment and have no problem so far.
Changes:
- Rename `numericString` to `NumericString` : This is usually a good pattern that every field of a public struct are made of purely public types. With this, we can easily build structs containing `NumericString` type in order to run tests and compare results.
- Modify `InApp.OriginalTransactionID` from `string` to `NumericString` : similarly to `ReceiptForIOS6.OriginalTransactionID`, this field is also worth using  `NumericString`. This also simplifies comparing the 2 …

Multiple fixes around NumericString type

---

playstore/validator.go
playstore/validator_test.go

Getting the following error in my codebase:
```
cannot use client (variable of type *playstore.Client) as playstore.IABSubscription value in assignment: *playstore.Client does not implement playstore.IABSubscription (wrong type for method DeferSubscription)
have DeferSubscription("context".Context, string, string, string, *androidpublisher.SubscriptionPurchasesDeferRequest) (*androidpublisher.SubscriptionPurchasesDeferResponse, error)
want DeferSubscription("context".Context, string, string, string, *androidpublisher.SubscriptionPurchasesDeferRequest) error
```

Align types for `DeferSubscription` method.

---

README.md

Docs: add some notes to app store server api

docs(readme): add notes to app store server api on readme

---

appstore/notification_v2.go

Fix the issue https://github.com/awa/go-iap/issues/266

feat(appstore): add more fields to JWSTransactionDecodedPayload 

---

appstore/api/model.go
appstore/notification_v2.go

fix VND price int32 overflow
example notification
```
{
...
"type": "Auto-Renewable Subscription",
"inAppOwnershipType": "PURCHASED",
"transactionReason": "PURCHASE",
"price": 4999000000,
"currency": "VND"
}
```

fix VND price int32 overflow

---

appstore/api/error.go
appstore/api/model.go

Per latest 1.11 release https://developer.apple.com/documentation/appstoreserverapi/app_store_server_api_changelog
> Added the [refundPreference](https://developer.apple.com/documentation/appstoreserverapi/refundpreference) field to the [ConsumptionRequest](https://developer.apple.com/documentation/appstoreserverapi/consumptionrequest) request body.
> Added the [InvalidTransactionTypeNotSupportedError](https://developer.apple.com/documentation/appstoreserverapi/invalidtransactiontypenotsupportederror) error object.

Feat(appstore): Add refundPreference and InvalidTransactionTypeNotSupportedError to appstore server api

---

playstore/notification.go

docs: https://developer.android.com/google/play/billing/rtdn-reference#voided-purchase

feat(playstore): add VoidedPurchaseRefundType

---

appstore/api/store.go
appstore/api/token.go

Try to fix https://github.com/awa/go-iap/issues/277

fix(appstore): Expose the TokenIssueAt and TokenExpireAt for appstore server api to prevent 401 when default server time is abnormal

---

appstore/api/token.go

Fix the issue that when the `ExpiredAt` is set and greater than the current time, the Bearer failed to initialize for the first time.

fix(appstore): Init the bearer when Bearer is empty

---

appstore/api/store.go
appstore/api/token.go

Related to issue https://github.com/awa/go-iap/issues/277

feat(appstore): replace issuedAt/expiredAt with issuedAtFunc/expiredAtFunc

---

appstore/api/token.go

docs: https://developer.apple.com/documentation/appstoreserverapi/generating_json_web_tokens_for_api_requests
In the existing code, time.Now() is called twice separately for issued_at and expired_at. This introduces the possibility of a time gap between these two calls. As a result, the difference between expired_at and issued_at might exceed 60 minutes.
By calling time.Now() only once and storing its value in a variable, we ensure that both issued_at and expired_at refer to the exact same point in time, thus maintaining the expected 60-minute difference between them.

fix(appstore): Use consistent timestamp for issued_at and expired_at

---

appstore/api/model.go
appstore/api/store.go

Support [1.12](https://developer.apple.com/documentation/appstoreserverapi/app_store_server_api_changelog#4408522)
New features
- Added the endpoint [Get Transaction History](https://developer.apple.com/documentation/appstoreserverapi/get_transaction_history), which provides transaction history for all in-app purchases, including consumable in-app purchases in a finished state.
- Added the fields [renewalPrice](https://developer.apple.com/documentation/appstoreserverapi/renewalprice), [currency](https://developer.apple.com/documentation/appstoreserverapi/currency), and [offerDiscountType](https://developer.apple.com/documentation/appstoreserverapi/offerdiscounttype) to the [JWSRenewalInfoDecodedPayload](https://developer.apple.com/documentation/appstoreserverapi/jwsrenewalinfodecodedpayloa …

feat(appstore): add get transaction history v2 and the fields renewalPrice, currency, and offerDiscountType to the JWSRenewalInfoDecodedPayload

---

appstore/cert.go

possible panic case if ios payment callback comes from unauthorised party instead of apple. Eg: malicious user or hacker

fix: possible panic case if ios payment callback comes from unauthorised party

---

playstore/mocks/playstore.go
playstore/validator.go

Related issue https://github.com/awa/go-iap/issues/292

fix(playstore): correct the number of parameters of VerifySubscriptionV2

---

playstore/mocks/playstore.go
playstore/validator.go
playstore/validator_test.go

Add the [monetization.subscriptions.get](https://developers.google.com/android-publisher/api-ref/rest/v3/monetization.subscriptions/get) method to the Play Store client.

feat(playstore): Add GetSubscription

---

README.md

This commit enhances the StoreConfig example in the README by providing more precise information about the location of the issuer ID in App Store Connect.

Improve StoreConfig example in README.md

---

appstore/notification_v2.go

These should be there according to the link below.
https://developer.apple.com/documentation/appstoreservernotifications/jwsrenewalinfodecodedpayload

feat(appstore): add two more fields to JWSRenewalInfoDecodedPayload

---

appstore/api/store.go

Hardcoded hosts complicate testability of the API layer.
It would be much easier to override the host when testing logic that uses this library, enabling the response to be mocked using tools like Wiremock or Postman.
As a solution, I propose a small change to allow configuring a debug host in the store settings.

feat(appstore): Add configurable host to store client

---

microsoftstore/model.go
microsoftstore/validator.go

Support window store per this doc https://learn.microsoft.com/en-us/windows/uwp/monetize/view-and-grant-products-from-a-service
related issue https://github.com/awa/go-iap/issues/307

feat: support window store

---

appstore/api/error.go
appstore/api/model.go

Per release note https://developer.apple.com/documentation/appstoreserverapi/app-store-server-api-changelog, add more fileds
-----
[1.15 - 2025/02/21](https://developer.apple.com/documentation/appstoreserverapi/app-store-server-api-changelog#115-20250221)
New features
Updated the [JWSRenewalInfoDecodedPayload](https://developer.apple.com/documentation/appstoreserverapi/jwsrenewalinfodecodedpayload) and [JWSTransactionDecodedPayload](https://developer.apple.com/documentation/appstoreserverapi/jwstransactiondecodedpayload) to include the new [appTransactionId](https://developer.apple.com/documentation/appstoreserverapi/apptransactionid) and [offerPeriod](https://developer.apple.com/documentation/appstoreserverapi/offerperiod) fields.
Updated the …

feat(appstore): add more fields

---

appstore/api/store.go

Related issue https://github.com/awa/go-iap/issues/312

fix(appstore): correct the parameter of GetTransactionHistory
