awa/go-iap

README.md
appstore/validator_test.go
playstore/validator_test.go

I did the unit tests for the error handling bits, so everything is now 100% covered. The unit tests for the normal scenario on GooglePlay are still missing, but the errors are handled.
I also updated the AppStore example in the README

Increased code coverage for the unit tests

---

README.md
playstore/validator.go
playstore/validator_test.go

This solves https://github.com/dogenzaka/go-iap/issues/5.

Use JSON credential of service account instead of oauth token

---

.travis.yml
amazon/validator.go
appstore/validator.go
appstore/validator_test.go
playstore/validator_test.go

resolve #22 
and fixed some failed tests

Fixed tests

---

appstore/validator.go
appstore/validator_test.go

Removed redundant error handling

---

README.md
appstore/model.go
appstore/validator.go
appstore/validator_test.go

Use interface argument for IAP response instead of the library defined struct

---

amazon/validator_test.go
appstore/validator.go
appstore/validator_test.go
playstore/validator_test.go

Use http package instead of gorequest

---

LICENSE
appstore/model.go
appstore/model_test.go

Handle type mismatch

---

appstore/model.go
appstore/notification.go

Fixed environment values

---

appstore/validator.go
appstore/validator_test.go

related: #30, #48, #60 
I've supported a custom http client to resolve above issues.

Support custom client for IAP

---

Makefile
playstore/validator.go
playstore/validator_test.go

resolve #30 
I've added ``NewWithClient()`` function to support GAE's urlfetch client.

Support custom http client for GAE

---

.travis.yml
Makefile
README.md
amazon/validator.go
amazon/validator_test.go

Support custom client for Amazon

---

appstore/notification.go

`DID_CHANGE_RENEWAL_PREFERENCE` was shortened
https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/StoreKitGuide/Chapters/Subscriptions.html

Update subscription notification type for IAP

---

appstore/model.go
appstore/notification.go

Add is_in_intro_offer_period in InApp & NotificationReceipt

---

.travis.yml
README.md
appstore/model_test.go
playstore/validator_test.go

Fixed test error

---

appstore/notification.go

#85 Added new const NotificationTypeDidChangeRenewalStatus

Added new const NotificationTypeDidChangeRenewalStatus

---

amazon/validator.go
amazon/validator_test.go

RVS Response examples: https://developer.amazon.com/docs/in-app-purchasing/iap-rvs-examples.html

 Added missing RVS Response Fields

---

playstore/validator_test.go

Fixed test error messages

---

playstore/notification.go

See https://developer.android.com/google/play/billing/realtime_developer_notifications#json_specification

Add more play store notification types

---

appstore/validator.go
appstore/validator_test.go

Fix appstore HandleError

---

appstore/model.go

Fixes: https://github.com/awa/go-iap/issues/71

Add missing fields in IAPResponseForIOS6

---

playstore/notification.go

Ref: https://developer.android.com/google/play/billing/rtdn-reference#json_specification

Update the developer notification struct to include one time products

---

appstore/validator.go
appstore/validator_test.go

Revert "increase default timeout for client"

---

appstore/notification.go

Three app store events have been added recently.
Doc: https://developer.apple.com/documentation/appstoreservernotifications/notification_type

Added new notification types for app store

---

appstore/model.go

This is to support the new subscription offer codes feature.
https://developer.apple.com/documentation/storekit/in-app_purchase/subscriptions_and_offers/implementing_offer_codes_in_your_app

Add OfferCodeRefName field to InApp and PendingRenewalInfo structs

---

appstore/notification.go

resolve #135 
https://developer.apple.com/documentation/appstoreservernotifications/responsebody
add some fields in reponse body
`bid` and `bvrs`

Add some field in responsebody

---

appstore/notification.go

As per the latest updates: https://developer.apple.com/news/?id=cjhooqcq

Appstore - Added REVOKE notification type

---

.gitignore
appstore/model.go
appstore/notification.go

Resolve: https://github.com/awa/go-iap/issues/140

add auto renew status change date in appstore subscription notification

---

appstore/notification.go

Added support for CONSUMPTION_REQUEST
https://developer.apple.com/documentation/appstoreservernotifications/notification_type

Added support for CONSUMPTION_REQUEST

---

appstore/model.go

Add Pre-Order date and time
App Store Doc:
[receipt](https://developer.apple.com/documentation/appstorereceipts/responsebody/receipt)

add PreorderDate type

---

appstore/model.go

- https://github.com/awa/go-iap/pull/151

Reveal in_app_ownership_type field of in-app section

---

.github/workflows/unit_test.yml
Makefile
appstore/model.go
appstore/notification.go
appstore/notification_v2.go
appstore/validator.go

- https://github.com/awa/go-iap/issues/149
- https://developer.apple.com/documentation/appstoreservernotifications/responsebodyv2

Add struct for v2 response of app store notification

---

appstore/model.go
appstore/notification.go

- https://github.com/awa/go-iap/issues/153

Modify field type of original_transaction_id to int64

---

appstore/model.go

Add missing field for receipt info.
https://developer.apple.com/documentation/appstorereceipts/app_account_token
Related to #152 issue

Add app_account_token field

---

appstore/notification_v2.go

notificationVersion to version
add signedDate
add JWSRenewalInfoDecodedPayload.RecentSubscriptionStartDate
Signed-off-by: Monkey <golang@88.com>

sync NotificationV2 struct according to apple.doc

---

amazon/validator.go
amazon/validator_test.go

Add more fields of amazon rvs response per doc https://developer.amazon.com/docs/in-app-purchasing/iap-rvs-for-android-apps.html

feat(amazon): add more fields of amazon rvs response

---

appstore/api/cert.go
appstore/api/store.go
appstore/model.go

New Feature: validate intermediate cert on appstore server api

feat: validate intermediate cert on appstore server api

---

playstore/testdata/test_key.json
playstore/validator.go
playstore/validator_test.go

Support Google Application Default Credentials in Play Store client

---

hms/client.go

Fix(hms): add error handling to json Unmarshal

fix(hms): add err handling to json Unmarshal

---

.github/workflows/tagging.yml

fix: fix workflow for tagging

---

playstore/validator.go
playstore/validator_test.go

Add voidedpurchases.list api to playstore per doc https://developers.google.com/android-publisher/api-ref/rest/v3/purchases.voidedpurchases/list

feat(playstore): add voidedpurchases.list api

---

README.md

Add ParseNotificationV2 api of appstore usage sample to readme

docs(readme): add ParseNotificationV2 of appstore usage sample to readme

---

amazon/notification.go

feat(amazon): add amazon notification model

---

appstore/api/model.go
appstore/api/store.go

Add get transaction info server API in docs: https://developer.apple.com/documentation/appstoreserverapi/get_transaction_info.

feat(appstore): add get transaction info

---

appstore/notification.go
appstore/notification_v2.go

This PR add some definations/annotations for app store notification according to the latest changelog documentd in https://developer.apple.com/documentation/appstoreservernotifications/app_store_server_notifications_changelog.

appstore server notification updates

---

appstore/api/model.go

feat(appstore): add more fields to JWSTransaction for app store server API per doc https://developer.apple.com/documentation/appstoreserverapi/jwstransactiondecodedpayload?changes=latest_minor

feat(appstore): add more fields to JWSTransaction for app store server api

---

appstore/api/store.go

We need an API to parse just one signedTransaction for some API like GetTransactionInfo

change parseSignedTransaction to public

---

appstore/api/model.go

feat(appstore): add more fields to the notification history of app server API per doc https://developer.apple.com/documentation/appstoreserverapi/notificationhistoryresponseitem?changes=latest_minor

feat(appstore): add more fields to notification history of app server api

---

appstore/api/model.go
appstore/api/store.go

feat(appstore): add more fields to request/response structs of app store server API per the latest app store server API document

feat(appstore): add more fields to request/response structs of app store server api

---

README.md

Add error handling of app store server api to readme

docs(readme): add error handling to readme

---

amazon/validator.go

ref: https://developer.amazon.com/docs/in-app-purchasing/rvs-cloud-sandbox.html

feat(amazon): amazon appstore default use rvs cloud sandbox endpoint

---

appstore/notification_v2.go

Fix the issue https://github.com/awa/go-iap/issues/243

fix(appstore): correct the AutoRenewStatus definition

---

playstore/notification.go

Reverts awa/go-iap#248
- the actual value is a string

Revert "fix(googleplay): fix type for eventTimeMillis"

---

appstore/api/model.go

https://developer.apple.com/documentation/appstoreserverapi/offertype

Make JWSRenewalInfoDecodedPayload.OfferType an int32 as in Apple documentation

---

appstore/notification_v2.go

https://developer.apple.com/documentation/appstoreservernotifications/subtype

add SubTypeV2Unreported

---

appstore/notification_v2.go

https://developer.apple.com/documentation/appstoreservernotifications/notificationtype#possibleValues

add NotificationTypeV2ExternalPurchaseToken

---

amazon/validator.go
amazon/validator_test.go

Per doc https://developer.amazon.com/docs/in-app-purchasing/iap-rvs-for-android-apps.html#rvs-response-fields-for-successful-transactions

feat(amazon): add more fields of amazon response

---

appstore/notification_v2.go

https://developer.apple.com/documentation/appstoreservernotifications/notificationtype#possibleValues
This was added on June 10th, 2024: https://developer.apple.com/documentation/appstoreservernotifications/app_store_server_notifications_changelog#4408521

Add NotificationTypeV2OneTimeCharge

---

playstore/notification.go

Per doc https://developer.android.com/google/play/billing/rtdn-reference, add SUBSCRIPTION_PENDING_PURCHASE_CANCELED notification type.

feat(playstore): add SUBSCRIPTION_PENDING_PURCHASE_CANCELED notification type
